<a href="https://colab.research.google.com/github/TarusinaDaria/practica-2/blob/main/%D0%94%D0%971.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises




File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
m_v = np.zeros((10,))
print(m_v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print("Size of the array: ",
      m_v.size)
 
print("Memory size of one array element in bytes: ",
      m_v.itemsize)
 
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      m_v.size * m_v.itemsize)

print("size of ndarray: ", m_v.nbytes)

Size of the array:  10
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 80
size of ndarray:  80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
m_vect = np.zeros((10,))
m_vect[4] = 1
print(m_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
rev_vec = vec[::-1]
print(rev_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
v = np.arange(0, 9)
v.shape = (3, 3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
ind_m = np.eye(3)
print(ind_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
rand_m = np.random.random((3,3,3))
print(rand_m)

[[[0.33382233 0.08928137 0.87837991]
  [0.63119549 0.76942067 0.57641275]
  [0.46315891 0.81152799 0.40526245]]

 [[0.84708648 0.41109269 0.38580693]
  [0.88273133 0.10228155 0.5072302 ]
  [0.1409359  0.95187206 0.98837337]]

 [[0.97960011 0.05552296 0.86964643]
  [0.76466561 0.2561879  0.21639112]
  [0.4013971  0.02802138 0.48839621]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
rand_arr = np.random.random((10,10))
min_r, max_r = rand_arr.min(), rand_arr.max()
print("array: ", rand_arr)
print(f"min = {min_r}, max = {max_r}")

array:  [[0.74500521 0.38197274 0.73625157 0.0512886  0.47744094 0.19125062
  0.26785512 0.15375423 0.35710079 0.29073009]
 [0.64464563 0.26826479 0.45621534 0.16600937 0.9550396  0.6056652
  0.20483512 0.60438778 0.68517425 0.51243049]
 [0.05288828 0.98250433 0.65462484 0.07897575 0.46818069 0.20702686
  0.30073348 0.04645556 0.14992114 0.60226347]
 [0.09229229 0.05311925 0.45396989 0.64184825 0.88196285 0.56730321
  0.09203592 0.20741497 0.88137303 0.68209021]
 [0.26206817 0.21661969 0.75598829 0.44761955 0.84355019 0.2956444
  0.79434019 0.65293469 0.58937459 0.16732311]
 [0.62247859 0.12886088 0.89799702 0.11445225 0.85295737 0.48457986
  0.94439781 0.07897513 0.29620445 0.70898909]
 [0.16303736 0.88162941 0.73018271 0.88538224 0.37700821 0.5903828
  0.74932958 0.88546469 0.88701998 0.03907975]
 [0.39829365 0.01216566 0.84560878 0.22457464 0.53579235 0.70141197
  0.31787622 0.03864487 0.93831052 0.52284057]
 [0.03346877 0.29094741 0.55359752 0.28771755 0.45378425 0.99303163
  0.556

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
rand_v = np.random.random(30)
avg = rand_v.mean()
print("vector: ", rand_v)
print("average element:", avg)

vector:  [0.74158959 0.20054938 0.81145952 0.32141826 0.99555197 0.82288129
 0.12982924 0.36212537 0.27884351 0.38880443 0.70358509 0.85092658
 0.99879369 0.34129197 0.12810738 0.5932347  0.86677306 0.78764825
 0.63016676 0.66986523 0.87365242 0.78604045 0.90837999 0.85730391
 0.12319769 0.89567984 0.86860224 0.20022304 0.02921782 0.29585138]
average element: 0.5820531343907686


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr_2 = np.ones((10,10))
arr_2[1:-1,1:-1] = 0
print(arr_2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones((10,10))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
diag_m = np.diag(1+np.arange(4),k=-1)
print(diag_m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
mart = np.ones((10,10), dtype=int)
mart[1::2,::2] = 0
mart[::2,1::2] = 0
print(mart)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.random((5,5))
print("matrix: ", matrix)
n_matr = (matrix - np.mean (matrix)) / (np.std (matrix))
print("normalize matrix: ", n_matr)

matrix:  [[0.72974118 0.44654981 0.82785503 0.1726394  0.55158858]
 [0.88985106 0.69462759 0.88798379 0.72750262 0.28535835]
 [0.10309177 0.68475807 0.36020864 0.39062463 0.49712533]
 [0.89146318 0.04433117 0.16778599 0.96766577 0.06762187]
 [0.412473   0.53707196 0.29383726 0.12626391 0.84069572]]
normalize matrix:  [[ 0.77571005 -0.19719357  1.11278005 -1.13821247  0.16366701]
 [ 1.32576735  0.65507734  1.31935234  0.76801949 -0.75096664]
 [-1.37714326  0.62117065 -0.49381857 -0.38932446 -0.02344142]
 [ 1.33130579 -1.57901523 -1.15488634  1.59309971 -1.49900005]
 [-0.31426441  0.11379517 -0.72183737 -1.29753538  1.15689423]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-29-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matr1 = np.arange(1,16)
matr1.shape = (5, 3)
print("matrix 1:\n", matr1)

matr2 = np.arange(1,7)
matr2.shape = (3, 2)
print("matrix 2:\n",matr2)

mul_matr = np.dot(matr1, matr2)
print("multiply matrix:\n", mul_matr)


matrix 1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
matrix 2:
 [[1 2]
 [3 4]
 [5 6]]
multiply matrix:
 [[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(-11, 12)
print(arr)

arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6
   7   8   9  10  11]
[-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3  -4  -5  -6
  -7   8   9  10  11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.array([1,2,3,4,5,6,7,8,9,10])
print("Z: ", Z)


a = Z**Z
print("Z**Z:", a)

a = 2 << Z >> 2
print("2 << Z >> 2:", a)

a = Z <- Z
print("Z <- Z:", a)

a = 1j*Z
print("1j*Z:", a)

a = Z/1/1
print("Z/1/1:", a)

#a = Z<Z>Z # ValueError
print("Z<Z>Z: # ValueError")


Z:  [ 1  2  3  4  5  6  7  8  9 10]
Z**Z: [          1           4          27         256        3125       46656
      823543    16777216   387420489 10000000000]
2 << Z >> 2: [  1   2   4   8  16  32  64 128 256 512]
Z <- Z: [False False False False False False False False False False]
1j*Z: [0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j]
Z/1/1: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Z<Z>Z: # ValueError


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-34-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-34-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.arange(-0.5, 0.5, 0.1)
print(arr)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[-5.00000000e-01 -4.00000000e-01 -3.00000000e-01 -2.00000000e-01
 -1.00000000e-01 -1.11022302e-16  1.00000000e-01  2.00000000e-01
  3.00000000e-01  4.00000000e-01]
[-1. -1. -1. -1. -1. -1.  1.  1.  1.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = np.array([24, 17, -3, 0, 10, 11, 15, -7, 14, 5])
arr2 = np.array([3, 4, -3, 0, 6, 11, 33, -10, 14, 8])
print(np.intersect1d(arr1, arr2))

[-3  0 11 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
_ = np.seterr(**defaults)

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-38-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2023-03-30
2023-03-31
2023-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.uniform(0,10,10)
print (arr - arr%1)
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr.astype(int))
print (np.trunc(arr))

[1. 6. 0. 2. 7. 4. 7. 6. 9. 9.]
[1. 6. 0. 2. 7. 4. 7. 6. 9. 9.]
[1. 6. 0. 2. 7. 4. 7. 6. 9. 9.]
[1 6 0 2 7 4 7 6 9 9]
[1. 6. 0. 2. 7. 4. 7. 6. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
m = np.zeros((5,5))
m += np.arange(5)
print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr_1 = np.linspace(0,1,11,endpoint=False)[1:]
print(arr_1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.random(10)
print(arr)
arr.sort()
print(arr)

[0.73159621 0.61785047 0.54576023 0.9559755  0.57547871 0.99266043
 0.79968132 0.6116523  0.86822911 0.81837037]
[0.54576023 0.57547871 0.6116523  0.61785047 0.73159621 0.79968132
 0.81837037 0.86822911 0.9559755  0.99266043]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.arange(10)
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array = np.zeros(10)
array.flags.writeable = False
array[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
matr = np.random.random((10,2))
X,Y = matr[:,0], matr[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.04834404 0.98709091 0.91974306 1.10271859 0.719249   0.85323224
 0.59314138 0.98004    1.03214577 1.38163673]
[1.18152683 0.34972871 1.07619483 0.56773946 0.90899702 0.19862796
 0.35744378 0.79565029 0.31763281 0.80486493]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
print(vec)

[0.69805794 0.85534007 0.96695694 0.20137387 0.36294121 0.63019207
 0.88807668 0.27291977 0.72914792 0.54785948]
[0.69805794 0.85534007 0.         0.20137387 0.36294121 0.63019207
 0.88807668 0.27291977 0.72914792 0.54785948]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.nan)
array = np.zeros((16,16))
print(array)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
X = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(X-v)).argmin()
print(X[index])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-59-57f8655657b5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
vec = np.random.random((10,2))
X,Y = np.atleast_2d(vec[:,0], vec[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.56714084 0.60326907 0.55312286 0.64365774 0.63822389
  0.56037124 0.42504699 0.20128718 0.07009804]
 [0.56714084 0.         0.56882013 0.51479335 0.52506401 0.43870156
  0.11536796 0.51503417 0.6203885  0.51167579]
 [0.60326907 0.56882013 0.         0.06052306 0.08746284 0.17500836
  0.6665628  0.17957613 0.78885922 0.53921755]
 [0.55312286 0.51479335 0.06052306 0.         0.09870339 0.15504975
  0.60991434 0.13731073 0.73490577 0.48747846]
 [0.64365774 0.52506401 0.08746284 0.09870339 0.         0.09790732
  0.62995567 0.23558153 0.81927574 0.57639318]
 [0.63822389 0.43870156 0.17500836 0.15504975 0.09790732 0.
  0.54761725 0.27038774 0.79901964 0.56866284]
 [0.56037124 0.11536796 0.6665628  0.60991434 0.62995567 0.54761725
  0.         0.59130678 0.57523168 0.51531847]
 [0.42504699 0.51503417 0.17957613 0.13731073 0.23558153 0.27038774
  0.59130678 0.         0.61466543 0.36277231]
 [0.20128718 0.6203885  0.78885922 0.73490577 0.81927574 0.79901964
  0.57523168 0.61466

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = array.view(np.int32)
Y[:] = array
print(Y)

[0 1 2 3 4 5 6 7 8 9]
[38 84 42 77 56  5 16 81  6  4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
str = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(str)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
    print(index, value)
for index in np.ndindex(array.shape):
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
array = np.zeros((n,n))
np.put(array, np.random.choice(range(n*n), p, replace=False),1)
print(array)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.39697158  0.30180656 -0.35307747 -0.4688686   0.30912365 -0.46188644
   0.42585739  0.23259866  0.42399121 -0.01257337]
 [-0.50504731 -0.24319043  0.21931796  0.33836425 -0.10949884 -0.216186
   0.34149702  0.03839909  0.04180026  0.094544  ]
 [ 0.104822   -0.3201685   0.34770449  0.33203619 -0.18750979  0.04784065
  -0.55404753  0.29673148 -0.08195775  0.01454876]
 [-0.27583329 -0.30775507  0.21466362  0.04296679  0.36716562  0.09661245
  -0.33607115 -0.25714563  0.04704034  0.40835632]
 [-0.07083352 -0.22023541 -0.09260575  0.13248908 -0.08221921  0.38724255
   0.14668619 -0.04026474  0.19409385 -0.35435304]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
array = np.random.randint(0,10,(3,3))
print(array)
print(array[array[:,1].argsort()])

[[1 8 3]
 [5 8 8]
 [6 5 4]]
[[6 5 4]
 [1 8 3]
 [5 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
array2d = np.random.randint(0,3,(3,10))
print((~array2d.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
array = np.random.uniform(0,1,10)
y = 0.5
x = array.flat[np.abs(array - y).argmin()]
print(x)

0.5717603127822464


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
array1 = np.arange(3).reshape(3,1)
array2 = np.arange(3).reshape(1,3)
it = np.nditer([array1,array2,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
array = NamedArray(np.arange(10), "range_10")
print (array.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vec1 = np.ones(10)
vec2 = np.random.randint(0,len(vec1),20)
vec1 += np.bincount(vec2, minlength=len(vec1))
print(vec1)
np.add.at(vec1, vec2, 1)
print(vec1)

[1. 1. 5. 2. 3. 3. 4. 4. 5. 2.]
[1. 1. 9. 3. 5. 5. 7. 7. 9. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
l = [1,3,9,3,4,1]
F = np.bincount(l,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
arr = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = arr[...,0]*256*256 + arr[...,1]*256 +arr[...,2]
n = len(np.unique(F))
print(np.unique(arr))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
X = np.random.randint(0,10,(3,4,3,4))
sum = X.sum(axis=(-2,-1))
print(sum)


sum = X.reshape(X.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[73 47 53 43]
 [63 67 58 45]
 [52 34 62 62]]
[[73 47 53 43]
 [63 67 58 45]
 [52 34 62 62]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.67973985 0.65527696 0.58797492 0.68238009 0.54900696 0.40262236
 0.52555669 0.51204006 0.43330547 0.63923466]
0    0.679740
1    0.655277
2    0.587975
3    0.682380
4    0.549007
5    0.402622
6    0.525557
7    0.512040
8    0.433305
9    0.639235
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

np.sum(A * B.T, axis=1)

np.einsum("ij,ji->i", A, B)

array([1.30378226, 1.64932551, 1.94540351, 1.60920425, 0.55418105])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
vec = np.array([1,2,3,4,5])
nz = 3
vec0 = np.zeros(len(vec) + (len(vec)-1)*(nz))
vec0[::nz+1] = vec
print(vec0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
array1 = np.ones((5,5,3))
array2 = 2*np.ones((5,5))
print(array1 * array2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
array = np.arange(25).reshape(5,5)
array[[0,1]] = array[[1,0]]
print(array)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 40) ( 2, 51) ( 3, 14) ( 3, 30) ( 4, 32) ( 4, 51) ( 6, 70) ( 6, 87)
 ( 9, 26) ( 9, 75) (14, 30) (17, 22) (17, 84) (20, 35) (20, 57) (22, 84)
 (26, 30) (26, 71) (26, 75) (26, 88) (26, 95) (30, 95) (32, 42) (32, 50)
 (32, 51) (35, 57) (40, 51) (42, 50) (70, 87) (71, 88)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
array = np.arange(20)
print(moving_average(array, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
array = np.random.randint(0,2,100)
np.logical_not(array, out=array)
array = np.random.uniform(-1.0,1.0,100)
np.negative(array, out=array)

array([-0.81149596, -0.91681065, -0.69555872,  0.26838507,  0.06883437,
        0.98046904, -0.86998369, -0.57267385, -0.03795299,  0.15916655,
       -0.64127717, -0.12375351,  0.78920316,  0.99134174,  0.97582372,
       -0.91666719, -0.58113295, -0.16055107,  0.15944809,  0.35165016,
        0.32711556, -0.64922416,  0.67390195, -0.63062955,  0.11035629,
        0.39421513, -0.35007396, -0.10550822,  0.39984323, -0.80296866,
        0.6069859 , -0.78629554, -0.87115696, -0.95509367,  0.09129407,
        0.59287802, -0.9780754 , -0.91974776, -0.80397265, -0.89271532,
       -0.08779869, -0.32234355, -0.79544854, -0.6540971 ,  0.33874561,
        0.36913297,  0.42580269,  0.62548957,  0.36022588, -0.55924603,
       -0.01245789,  0.11141935,  0.65121967, -0.73800386, -0.51495537,
       -0.72430745, -0.59524996,  0.29638505, -0.03550677,  0.31473038,
        0.00948966,  0.01570924,  0.53689038, -0.33782359,  0.16432582,
       -0.50434527,  0.99822535, -0.21671648,  0.02120211, -0.35

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.14723594  1.73264471  3.95344851  0.65414653  0.20477488  4.23509213
 11.07876929  1.63525523  3.84313535  6.00842389]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.25786038  5.10161876  2.11803328  2.91155915  7.67190638  3.15030334
   1.95608334  2.14522325  0.90675715  2.94333685]
 [ 1.34719567 12.96339155  6.593002    0.47727307 15.87096034  3.60532807
   2.67276506  8.17873841  5.03878853  0.75787154]
 [ 2.15430778  6.85765524  4.00509188  1.10417986  8.66646128  4.60246797
   0.06057653  2.14724729  0.93339607  1.10968626]
 [ 4.82024619  8.8330731   1.3353054   4.74339735 14.3041117   1.05684876
   2.5808745   9.41605647  6.35184386  4.48443661]
 [ 4.46801502  9.59240233  7.49478665  2.36255847  9.69588753  7.70229098
   3.42618393  1.31512244  1.81575399  2.37096243]
 [ 2.86986641 10.47415357  3.76679096  2.2637547  14.60375293  1.31668838
   0.16100394  8.40518693  5.30740379  2.0129832 ]
 [11.18302577  0.95445236  3.42472174  0.10448374  3.1262841  10.03371701
   0.9067842   9.71027989 12.74277672  0.40093739]
 [ 2.61539057  0.37111186  3.8409506   8.816622    5.81823346  2.09390099
   7.9122527   3.46723784  0.50136327  8.87625613]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
array = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=array.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(array.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = array[z]
print(array)
print(R)

[[5 4 1 4 9 6 0 3 9 1]
 [5 8 6 3 9 2 7 9 5 9]
 [3 6 7 8 3 4 4 0 2 3]
 [4 8 9 2 1 6 8 0 4 7]
 [7 9 4 1 0 6 8 6 3 5]
 [8 8 1 1 7 0 0 4 5 4]
 [6 3 0 2 6 2 8 1 5 7]
 [6 3 6 1 4 8 2 9 8 6]
 [1 7 5 8 9 4 0 4 3 6]
 [5 9 3 1 7 5 8 7 4 1]]
[[0 0 0 0 0]
 [0 5 4 1 4]
 [0 5 8 6 3]
 [0 3 6 7 8]
 [0 4 8 9 2]]


<ipython-input-88-5b40f7b64231>:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = array[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
matrix = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(matrix) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (matrix.shape[0]-3)
j = 1 + (matrix.shape[1]-3)
C = stride_tricks.as_strided(matrix, shape=(i, j, n, n), strides=matrix.strides + matrix.strides)
print(C)

[[[[2 3 0]
   [1 3 0]
   [3 3 2]]

  [[3 0 4]
   [3 0 1]
   [3 2 3]]

  [[0 4 1]
   [0 1 4]
   [2 3 2]]

  [[4 1 0]
   [1 4 0]
   [3 2 1]]

  [[1 0 4]
   [4 0 4]
   [2 1 0]]

  [[0 4 1]
   [0 4 0]
   [1 0 3]]

  [[4 1 2]
   [4 0 2]
   [0 3 1]]

  [[1 2 4]
   [0 2 3]
   [3 1 0]]]


 [[[1 3 0]
   [3 3 2]
   [2 2 1]]

  [[3 0 1]
   [3 2 3]
   [2 1 4]]

  [[0 1 4]
   [2 3 2]
   [1 4 0]]

  [[1 4 0]
   [3 2 1]
   [4 0 2]]

  [[4 0 4]
   [2 1 0]
   [0 2 4]]

  [[0 4 0]
   [1 0 3]
   [2 4 2]]

  [[4 0 2]
   [0 3 1]
   [4 2 2]]

  [[0 2 3]
   [3 1 0]
   [2 2 2]]]


 [[[3 3 2]
   [2 2 1]
   [2 2 3]]

  [[3 2 3]
   [2 1 4]
   [2 3 0]]

  [[2 3 2]
   [1 4 0]
   [3 0 1]]

  [[3 2 1]
   [4 0 2]
   [0 1 1]]

  [[2 1 0]
   [0 2 4]
   [1 1 0]]

  [[1 0 3]
   [2 4 2]
   [1 0 2]]

  [[0 3 1]
   [4 2 2]
   [0 2 4]]

  [[3 1 0]
   [2 2 2]
   [2 4 3]]]


 [[[2 2 1]
   [2 2 3]
   [0 2 4]]

  [[2 1 4]
   [2 3 0]
   [2 4 3]]

  [[1 4 0]
   [3 0 1]
   [4 3 4]]

  [[4 0 2]
   [0 1 1]
   [3 4 2]]

  [[0 2 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  9  3  6  8]
 [ 9  7  6  5  5]
 [ 3  6  8 42  8]
 [ 6  5 42  8  4]
 [ 8  5  8  4  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
array = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], k), axis=0),
                                       np.arange(0, array.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(array):
    # Count neighbours
    N = (array[0:-2,0:-2] + array[0:-2,1:-1] + array[0:-2,2:] +
         array[1:-1,0:-2]                + array[1:-1,2:] +
         array[2:  ,0:-2] + array[2:  ,1:-1] + array[2:  ,2:])
    # Apply rules
    birth = (N==3) & (array[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (array[1:-1,1:-1]==1)
    array[...] = 0
    array[1:-1,1:-1][birth | survive] = 1
    return Z
array = np.random.randint(0,2,(50,50))
for i in range(100): array = iterate(array)
print(array)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
array = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (array[np.argsort(array)[-n:]])

print (array[np.argpartition(-array,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9998 9997 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
array = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(array.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.random.rand(int(5e7))
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

827 ms ± 145 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
95.9 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
91.7 ms ± 4.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
matrix = np.random.randint(0,5,(10,3))
print(matrix)

E = np.all(matrix[:,1:] == matrix[:,:-1], axis=1)
U = matrix[~E]
print(U)

U = matrix[matrix.max(axis=1) != matrix.min(axis=1),:]
print(U)

[[2 4 0]
 [3 4 0]
 [4 1 3]
 [4 3 0]
 [1 2 1]
 [2 0 2]
 [1 4 0]
 [1 1 2]
 [3 1 0]
 [2 4 2]]
[[2 4 0]
 [3 4 0]
 [4 1 3]
 [4 3 0]
 [1 2 1]
 [2 0 2]
 [1 4 0]
 [1 1 2]
 [3 1 0]
 [2 4 2]]
[[2 4 0]
 [3 4 0]
 [4 1 3]
 [4 3 0]
 [1 2 1]
 [2 0 2]
 [1 4 0]
 [1 1 2]
 [3 1 0]
 [2 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(array).view(np.dtype((np.void, array.dtype.itemsize * array.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = array[idx]
print(uZ)

uZ = np.unique(array, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.21118331, 0.25038938, 0.04353678, 0.13680739, 0.19500757,
        0.01818565, 0.15000447, 0.19620081, 0.26549917, 0.26540383],
       [0.20668584, 0.24505695, 0.0426096 , 0.13389386, 0.19085458,
        0.01779835, 0.14680989, 0.19202241, 0.25984496, 0.25975164],
       [0.34210346, 0.40561478, 0.0705268 , 0.22161921, 0.31589979,
        0.02945958, 0.24299764, 0.31783276, 0.43009168, 0.42993722],
       [0.37113471, 0.44003567, 0.07651178, 0.24042605, 0.34270738,
        0.03195955, 0.26361867, 0.34480438, 0.4665897 , 0.46642214],
       [0.2565019 , 0.30412134, 0.0528795 , 0.16616538, 0.23685495,
        0.02208817, 0.18219447, 0.23830425, 0.3224736 , 0.32235779],
       [0.27889511, 0.33067184, 0.057496  , 0.180672  , 0.25753294,
        0.02401652, 0.19810047, 0.25910877, 0.35062629, 0.35050038],
       [0.69304818, 0.8217122 , 0.14287629, 0.44896592, 0.63996364,
        0.05968051, 0.49227527, 0.64387954, 0.87129857, 0.87098567],
       [0.21754032, 0.25792657, 0.0448473

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1856195   0.22199207]
